/**
 * Identifier helpers. Archive ids and request ids are local UUIDv4 values
 * generated by this plugin; nothing is ever derived from a source id.
 * @module dsh-chat-bridge/shared/ids
 */

const UUID_V4 = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i

/**
 * Generate a new local identifier.
 * @returns a lowercase UUIDv4 string.
 */
export function newLocalId(): string {
  return globalThis.crypto.randomUUID()
}

/**
 * Whether a string is a UUIDv4 as produced by {@link newLocalId}.
 * @param value - candidate string.
 * @returns true for a well-formed v4 UUID.
 */
export function isLocalId(value: string): boolean {
  return UUID_V4.test(value)
}
